revision:   "018--05-Aug-2021"
copyright:  "2021-2021"
title:      "Main Title"
author:     "Cicak Bin Kadal"
lang:       "en-US"
description:
  "Description:
   I have spoken."
disclaimer:
   "Disclaimer:
   I have spoken."
navbarlinks:
- navbar:   "Home"
  link:     "/"
- navbar:   "Links"
  link:     "/links.html"
- navbar:   "About"
  link:     "/about.html"
- navbar:   "GitHub"
  link:     "https://github.com/webjekyll/coba/"
- navbar:   "GitHub Page"
  link:     "https://webjekyll.github.io/coba/"
plugins:
defaults:
- scope:
    path:   ""
  values:
    layout: "default"
markdown:   "kramdown"
google_analytics: UA-89852122-15
github:
- metadata
