version:  "016--02-Aug-2021"
lang:     "en-US"
description:
   I have spoken description.
disclaimer:
   I have spoken disclaimer.
navbarlinks:
- navbar: "Home"
  link:   "/"
- navbar: "About"
  link:   "/about.html"
- navbar: "GitHub"
  link:   "https://github.com/webjekyll/coba/"
- navbar: "GitHub Page"
  link:   "https://webjekyll.github.io/coba/"
plugins:
defaults:
- scope:
    path: ""
  values:
    layout: "default"
markdown: "kramdown"
google_analytics: UA-89852122-15
github:
- metadata
