version:  "015--01-Aug-2021"
lang:     "en-US"
description:
   I have spoken.
navbarlinks:
- navbar: "Home"
  link:   "/"
- navbar: "About"
  link:   "/about.html"
plugins:
defaults:
- scope:
    path: ""
  values:
    layout: "default"
markdown: "kramdown"
google_analytics: UA-89852122-15
baseurl: ""
github: [metadata]
