revision:   "023--10-Aug-2021"
copyright:  "2021-2021"
title:      "The Main Title"
author:     "Mr. Author"
lang:       "en-US"
description:
  "Description:
   I have spoken."
disclaimer:
   "Disclaimer:
   I have spoken."
navbarlinks:
- navbar:   "Home"
  link:     "/"
- navbar:   "Tester"
  link:     "/tester.html"
- navbar:   "Tester1"
  link:     "/tester1.html"
- navbar:   "Links"
  link:     "/links.html"
- navbar:   "About"
  link:     "/about.html"
- navbar:   "GitHub"
  link:     "https://github.com/webjekyll/coba/"
- navbar:   "GitHub Page"
  link:     "https://webjekyll.github.io/coba/"
plugins:
defaults:
- scope:
    path:   ""
  values:
    layout: "default"
markdown:   "kramdown"
google_analytics: UA-89852122-15
github:
- metadata
