version: "008--01-Aug-2021"
# baseurl
markdown: "kramdown"
plugins:
defaults:
- scope:
    path: ""
  values:
    layout: "default"
navbarlinks:
- navbar: "Home"
  link:   "/"
- navbar: "About"
  link:   "/about.html"

